create table public.cart_item
(
    quantity   integer,
    cart_id    bigint
        constraint fk1uobyhgl1wvgt1jpccia8xxs3
            references public.cart,
    id         bigint generated by default as identity
        primary key,
    product_id bigint
        constraint fk6ho67qee1ktpal6cj88l6tv0f
            references public.spare_parts
);

alter table public.cart_item
    owner to postgres;

