create table public.order_list
(
    id                 bigint generated by default as identity
        primary key,
    order_date         timestamp(6),
    status_change_date timestamp(6),
    user_id            bigint
        constraint fk5sy9tcmivmr7s63b82uqfp5g1
            references public.users,
    order_status       varchar(255)
        constraint order_list_order_status_check
            check ((order_status)::text = ANY
                   ((ARRAY ['CREATED'::character varying, 'ACCEPTED'::character varying, 'DISPATCHED'::character varying, 'DELIVERED'::character varying])::text[]))
);

alter table public.order_list
    owner to postgres;

