create table public.order_item
(
    price      numeric(38, 2),
    quantity   integer not null,
    id         bigint generated by default as identity
        primary key,
    order_id   bigint
        constraint fk26hiw9s4k2sjmfvlxnyibj46c
            references public.order_list,
    product_id bigint
        constraint fkoj5r018lw23e78ygir48ulhde
            references public.spare_parts
);

alter table public.order_item
    owner to postgres;

