create table public.cart
(
    id      bigint generated by default as identity
        primary key,
    user_id bigint
        constraint fkg5uhi8vpsuy0lgloxk2h4w5o6
            references public.users
);

alter table public.cart
    owner to postgres;

